LOGIN_LINK_LOCATOR = "//a[text()='Log in']"
LOGIN_EMAIL_LOCATOR = "name:Email"
LOGIN_PASSWORD_LOCATOR = "name:Password"
LOGIN_BUTTON_LOCATOR = "//input[@value='Log in']"
EMAIL = "Nomind@gmail.com"
PASSWORD = "nomind"