REGISTER_LINK_LOCATOR = "//a[text()='Register']"
GENDER_RADIOBUTTON_LOCATOR = "name:Gender"
FIRST_NAME_LOCATOR= "id:FirstName"
LAST_NAME_LOCATOR = "id:LastName"
EMAIL_LOCATOR = "name:Email"
PASSWORD_LOCATOR = "id:Password"
CONFIRM_PASSWORD = "id:ConfirmPassword"
REGISTER_BUTTON_LOCATOR = "id:register-button"
COMPLETE_MESSAGE_LOCATOR = "//div[contains(text(),' Your registration completed')]"
CONTINUE_BUTTON_LOCATOR = "//input[@value='Continue']"
